//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWebRole.AzureServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AzureServices.IHolaService")]
    public interface IHolaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolaService/GetSaludo", ReplyAction="http://tempuri.org/IHolaService/GetSaludoResponse")]
        string GetSaludo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolaService/GetSaludo", ReplyAction="http://tempuri.org/IHolaService/GetSaludoResponse")]
        System.Threading.Tasks.Task<string> GetSaludoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHolaServiceChannel : PruebaWebRole.AzureServices.IHolaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HolaServiceClient : System.ServiceModel.ClientBase<PruebaWebRole.AzureServices.IHolaService>, PruebaWebRole.AzureServices.IHolaService {
        
        public HolaServiceClient() {
        }
        
        public HolaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HolaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSaludo() {
            return base.Channel.GetSaludo();
        }
        
        public System.Threading.Tasks.Task<string> GetSaludoAsync() {
            return base.Channel.GetSaludoAsync();
        }
    }
}
